update CI

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -3,7 +3,7 @@ name: Build and Push Docker Image
 on:
   push:
     branches:
-      - main  # Trigger to push event
+      - main
 
 jobs:
   build:
@@ -11,8 +11,8 @@ jobs:
 
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v3
-      
+        uses: actions/checkout@v4
+
       # CI
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -30,18 +30,24 @@ jobs:
       #   run: yarn run test
 
       # CD
-
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+        uses: docker/setup-buildx-action@v3
+
+      - name: Validate Docker Hub Username
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "Error: DOCKERHUB_USERNAME is not set"
+            exit 1
+          fi
 
       - name: Login to Docker Hub
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
       - name: Build and Push Docker Image
-        uses: docker/build-push-action@v4
+        uses: docker/build-push-action@v6
         with:
           context: .
           push: true
@@ -49,11 +55,11 @@ jobs:
 
       - name: Update deployment.yaml
         run: |
-          sed -i 's|image:.*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/msa-fe:${{ github.sha }}|' k8s/deployment.yaml
+          sed -i "s|image:.*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/msa-fe:${{ github.sha }}|" k8s/deployment.yaml
           git config user.name "GitHub Action"
           git config user.email "action@github.com"
           git add k8s/deployment.yaml
           git commit -m "Update image tag to ${{ github.sha }}"
           git push
         env:
-          GITHUB_TOKEN: \${{ secrets.MY_TOKEN }}
+          GITHUB_TOKEN: ${{ github.token }}
